// @flow

import type { PointCodeT } from '../../types/Point'

export const m: PointCodeT = 'm'
export const M: PointCodeT = 'M'
export const l: PointCodeT = 'l'
export const L: PointCodeT = 'L'
export const h: PointCodeT = 'h'
export const H: PointCodeT = 'H'
export const v: PointCodeT = 'v'
export const V: PointCodeT = 'V'
export const q: PointCodeT = 'q'
export const Q: PointCodeT = 'Q'
export const t: PointCodeT = 't'
export const T: PointCodeT = 'T'
export const c: PointCodeT = 'c'
export const C: PointCodeT = 'C'
export const s: PointCodeT = 's'
export const S: PointCodeT = 'S'
export const a: PointCodeT = 'a'
export const A: PointCodeT = 'A'
export const z: PointCodeT = 'z'
export const Z: PointCodeT = 'Z'
