// @flow

export const CONFIG = {
  SEGS: {
    TYPES: {
      "": 0,
      Z: 1,
      z: 1,
      M: 2,
      m: 3,
      L: 4,
      l: 5,
      C: 6,
      c: 7,
      Q: 8,
      q: 9,
      A: 10,
      a: 11,
      H: 12,
      h: 13,
      V: 14,
      v: 15,
      S: 16,
      s: 17,
      T: 18,
      t: 19,
    },
    DEFS: [
      {
        type: "",
        isAbs: false,
        isRel: false,
        params: [],
        defs: {},
      },
      {
        type: "z",
        isAbs: true,
        isRel: true,
        params: ["cmd"],
        defs: {
          cmd: { index: 0 },
        },
      },
      {
        type: "M",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
      {
        type: "m",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
      {
        type: "L",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
      {
        type: "l",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
      {
        type: "C",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x1", "y1", "x2", "y2", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x1: { index: 1 },
          y1: { index: 2 },
          x2: { index: 3 },
          y2: { index: 4 },
          x: { index: 5 },
          y: { index: 6 },
        },
      },
      {
        type: "c",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x1", "y1", "x2", "y2", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x1: { index: 1 },
          y1: { index: 2 },
          x2: { index: 3 },
          y2: { index: 4 },
          x: { index: 5 },
          y: { index: 6 },
        },
      },
      {
        type: "Q",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x1", "y1", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x1: { index: 1 },
          y1: { index: 2 },
          x: { index: 3 },
          y: { index: 4 },
        },
      },
      {
        type: "q",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x1", "y1", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x1: { index: 1 },
          y1: { index: 2 },
          x: { index: 3 },
          y: { index: 4 },
        },
      },
      {
        type: "A",
        isAbs: true,
        isRel: false,
        params: [
          "cmd",
          "rx",
          "ry",
          "angle",
          "largeArcFlag",
          "sweepFlag",
          "x",
          "y",
        ],
        defs: {
          cmd: { index: 0 },
          rx: { index: 1 },
          ry: { index: 2 },
          angle: { index: 3 },
          largeArcFlag: { index: 4 },
          sweepFlag: { index: 5 },
          x: { index: 6 },
          y: { index: 7 },
        },
      },
      {
        type: "a",
        isAbs: false,
        isRel: true,
        params: [
          "cmd",
          "rx",
          "ry",
          "angle",
          "largeArcFlag",
          "sweepFlag",
          "x",
          "y",
        ],
        defs: {
          cmd: { index: 0 },
          rx: { index: 1 },
          ry: { index: 2 },
          angle: { index: 3 },
          largeArcFlag: { index: 4 },
          sweepFlag: { index: 5 },
          x: { index: 6 },
          y: { index: 7 },
        },
      },
      {
        type: "H",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
        },
      },
      {
        type: "h",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
        },
      },
      {
        type: "V",
        isAbs: true,
        isRel: false,
        params: ["cmd", "y"],
        defs: {
          cmd: { index: 0 },
          y: { index: 1 },
        },
      },
      {
        type: "v",
        isAbs: false,
        isRel: true,
        params: ["cmd", "y"],
        defs: {
          cmd: { index: 0 },
          y: { index: 1 },
        },
      },
      {
        type: "S",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x2", "y2", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x2: { index: 1 },
          y2: { index: 2 },
          x: { index: 3 },
          y: { index: 4 },
        },
      },
      {
        type: "s",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x2", "y2", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x2: { index: 1 },
          y2: { index: 2 },
          x: { index: 3 },
          y: { index: 4 },
        },
      },
      {
        type: "T",
        isAbs: true,
        isRel: false,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
      {
        type: "t",
        isAbs: false,
        isRel: true,
        params: ["cmd", "x", "y"],
        defs: {
          cmd: { index: 0 },
          x: { index: 1 },
          y: { index: 2 },
        },
      },
    ],
  },
};
